"""baseline check

Revision ID: c002697e0070
Revises:
Create Date: 2026-08-11 15:29:42.293296

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "c002697e0070"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "characters",
        "status",
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.Enum("alive", "deceased", "missing", name="characterstatus"),
        existing_nullable=True,
    )
    op.alter_column(
        "monsters",
        "threat_level",
        existing_type=mysql.VARCHAR(length=20),
        type_=sa.Enum("low", "medium", "high", "extreme", name="monsterthreatlevel"),
        existing_nullable=True,
    )
    op.alter_column(
        "quests",
        "status",
        existing_type=mysql.VARCHAR(length=20),
        type_=sa.Enum("pending", "in_progress", "completed", "failed", name="queststatus"),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quests",
        "status",
        existing_type=sa.Enum("pending", "in_progress", "completed", "failed", name="queststatus"),
        type_=mysql.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "monsters",
        "threat_level",
        existing_type=sa.Enum("low", "medium", "high", "extreme", name="monsterthreatlevel"),
        type_=mysql.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "characters",
        "status",
        existing_type=sa.Enum("alive", "deceased", "missing", name="characterstatus"),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
